### ISSUE TITLE
setXmlValue throws XmlException in some cases

### ISSUE THREAD

**Issue by ttustonic** [Bluegrams/SettingsProviders#3]
Hello
A method `setXmlValue `throws `XmlException `when serialized value is empty string. 

The test case is in the attachment.

To fix, in `PortableSettingsProvider.cs `change 
`if (value.SerializedValue == null) serialized = new XText("");`
to 
` if ((value.SerializedValue is string && String.IsNullOrWhiteSpace(value.SerializedValue as string)) ||value.SerializedValue == null)
                serialized = new XText("");
`

[xmlexctest.zip](https://github.com/Bluegrams/SettingsProviders/files/3415167/xmlexctest.zip)

**Comment by alxnull** [comment]
Thanks for your detailed error description. I pushed your test case and the suggested fix in cdb7e02d715c90a0533bd744c81b4248022255ba.
