### ISSUE TITLE
.NET Core Compatibility

### ISSUE THREAD

**Issue by ArvinZJC** [Bluegrams/SettingsProviders#5]
When I try to use your brilliant customised settings provides in my WPF project with .NET Core 3.1, it will have the following warning:

Package 'PortableSettingsProvider 0.2.3' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.

Although I do not encounter any compatibility issues for now, is there any plan to support the .NET Core framework?

**Comment by alxnull** [comment]
Hi, glad you find this useful. I currently don't see any issues why this shouldn't work with .NET Core as is. I'll add `netstandard2.0` as a target framework and push a new version.
